server:
  port: 8080

spring:
  application:
    name: knowledge-hub

  # --- 1. НАСТРОЙКИ НА БАЗАТА ДАННИ ---
  datasource:
    url: jdbc:postgresql://localhost:5435/ai_knowledge_hub_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  # --- 2. ИНИЦИАЛИЗАЦИЯ (За да се пусне vector extension-a)
  sql:
    init:
      mode: always # <--- ВАЖНО: Задължително пуска schema.sql при старт

  # --- 3. HIBERNATE / JPA ---
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: false # Пуска schema.sql ПРЕДИ Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # --- 4. ЛИМИТИ ЗА КАЧВАНЕ НА ФАЙЛОВЕ ---
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # --- 5. SPRING AI НАСТРОЙКИ ---
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

    # Вектори: Локално генериране
    embedding:
      transformer:
        enabled: true

# --- 6. LOGGING ---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE